### ISSUE TITLE
Publish on MELPA?

### ISSUE THREAD

**Issue by kir0ul** [ki-chi/julia-formatter#9] opened 2021-12-07 20:46 UTC
Hi there,

Thanks for this package!

I was wondering if you would consider publishing it to [MELPA](https://melpa.org/) so that it's easier to install and update?

**Comment by ki-chi** [comment] 2021-12-10 17:24
Sounds good.

I'm not familiar with the development of the Emacs package, mainly including miscellaneous files like Julia scripts, so I need to start learning about it. It may take some time, but I will try.

Or, if you have any PR, this is a great place to start.

**Comment by kir0ul** [comment] 2021-12-11 17:38
> I'm not familiar with the development of the Emacs package, mainly including miscellaneous files like Julia scripts, so I need to start learning about it. It may take some time, but I will try.

Sure, no rush :raised_hands: 

> Or, if you have any PR, this is a great place to start.

Sorry I know nothing about how MELPA works either, I'm just a simple user :grimacing: 


Also maybe you want to have a look at https://github.com/melpa/melpa/pull/7815, they're trying to have their package merged into MELPA, and it seems your package is pretty similar to theirs.

**Comment by ki-chi** [comment] 2021-12-12 00:56
What a surprise. I didn't know that similar packages existed until just now. (My package was last updated two years ago....)
It seems more sophisticated than mine and should be registered in MELPA 😂

I'll try to improve the process of installation of my package with the combination of `use-package.el` and `straight.el`:
```
(use-package julia-formatter
  :straight (el-patch :type git :host github :repo "ki-chi/julia-formatter"
```
or `leaf.el`:
```
(leaf julia-formatter :el-get ki-chi/julia-formatter)
```

However, I will not register mine to MELPA for a while to avoid confusion caused by similar packages.
Close this issue. Thanks for your attention.

**Closed as completed by ki-chi** 2021-12-12 00:56 UTC
Labels: enhancement
